### ISSUE TITLE
Demo project not loading.

### ISSUE THREAD

**Issue by GGIEnrike** [jprendes/emception#5] opened 2022-05-19 16:32 UTC
After discovering Emception project, I quickly opened up the provided demo on [this](https://jprendes.github.io/emception/) link, but what I got was a loading icon that won't disappear no matter how long I wait for.

I am running Chrome, Version 101.0.4951.64 (Official Build) (x86_64), on MacOS, if that's any useful. Is there a known problem? Or how could I debug it to help you at least figure out what goes wrong?

I will soon be trying to build it myself to test if it actually works, but now I just don't have time for that.

**Comment by GGIEnrike** [comment] 2022-05-19 21:14
UPDATE: I got it working on Firefox. Compiled a couple of code snippets, all seems to work fine. Don

**Comment by GGIEnrike** [comment] 2022-05-19 21:18
UPDATE: I managed to get it working on Firefox without a hiccup. I have compiled a couple of code snippets and all seems to work as expected. I'm still kind of blown of it's all being done on the client-side. Don't know what caused Chrome to not work, although Chrome would usually be worse with new features.

**Comment by samuel-fiedler** [comment] 2022-05-24 17:15
The problem in Firefox is that IndexedDB experimental isn't enabled. To enable it, go to about:config, search for indexeddb and set all results to "true". I hope it helps!

**Comment by mingodad** [comment] 2022-12-14 08:58
After build the demo project and changing the string "hello world!\n" to "hello world2!\n" it stopped working.

**Comment by jprendes** [comment] 2023-02-13 22:46
I observe a problem win chrome when running without the devtools open.
I can't reproduce in Firefox.
@GGIEnrike, are you running Chrom(ium)? Does it work if you open the dev-tools before loading the website?

**Comment by jprendes** [comment] 2023-03-14 07:05
Closing this issue since as I believe this is now fixed. Feel free to reopen it if that's not the case.

**Closed by jprendes** 2023-03-14 07:05 UTC
